#!/bin/bash
SREF=".$(basename $SHELL)rc"
if [ ! -d ~/bin ]
then
	mkdir ~/bin && mkdir ~/bin/norme
else
	if [ ! -d ~/bin/norme ]
	then
		mkdir ~/bin/norme
	fi
fi && cp hnorm ~/bin/norme && cd .. && rm -rf HBPC && cd ~/bin/norme

if [ -f ~/$SREF ]
then
	if [[ `cat ~/$SREF | grep "alias hnorm='~/bin/norme/hnorm'"` == "" ]]
	then
		printf "\nalias hnorm='~/bin/norme/hnorm'\n" >> ~/$SREF
		source ~/$SREF
	fi
	source ~/$SREF
fi 2> /dev/null

cd
~/bin/norme/hnorm -h

printf "\033[92mInstallation Successful !\n\033[93mPlease enter:\033[0m cd .. ; source $SREF \n"
