#!/bin/bash
if [ ! -d ~/bin ]
then
	mkdir ~/bin && mkdir ~/bin/norme
else
	if [ ! -d ~/bin/norme ]
	then
		mkdir ~/bin/norme
	fi
fi && cp hnorm ~/bin/norme && cd .. && rm -rf HBPC && cd ~/bin/norme

if [ -f ~/.zshrc ]
then
	if [[ `cat ~/.zshrc | grep "alias hnorm='~/bin/norme/hnorm'"` == "" ]]
	then
		printf "\nalias hnorm='~/bin/norme/hnorm'\n" >> ~/.zshrc
		source ~/.zshrc
	fi
	source ~/.zshrc
elif [ -f ~/.bashrc ]
then
	if [[ `cat ~/.bashrc | grep "alias hnorm='~/bin/norme/hnorm'"` == "" ]]
	then
		printf "\nalias hnorm='~/bin/norme/hnorm'\n" >> ~/.bashrc
		source ~/.bashrc
	fi
	source ~/.bashrc
fi 2> /dev/null

cd ..
printf "\033[92mInstallation Successful !\n\033[0m"
